weeks:
  1:
    judge_score: week1_judge_score
    judge_percent: 1_percent
  2:
    judge_score: week2_judge_score
    judge_percent: 2_percent
  3:
    judge_score: week3_judge_score
    judge_percent: 3_percent
  4:
    judge_score: week4_judge_score
    judge_percent: 4_percent
  5:
    judge_score: week5_judge_score
    judge_percent: 5_percent
  6:
    judge_score: week6_judge_score
    judge_percent: 6_percent
  7:
    judge_score: week7_judge_score
    judge_percent: 7_percent
  8:
    judge_score: week8_judge_score
    judge_percent: 8_percent
  9:
    judge_score: week9_judge_score
    judge_percent: 9_percent
  10:
    judge_score: week10_judge_score
    judge_percent: 10_percent
  11:
    judge_score: week11_judge_score
    judge_percent: 11_percent
